# Generated by Django 6.1.1 on 2026-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefas",
            name="data_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data de inicio"
            ),
        ),
        migrations.AddField(
            model_name="tarefas",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tarefas",
            name="prioridade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tarefas",
            name="status",
            field=models.CharField(default="aberta", max_length=50),
        ),
        migrations.AddField(
            model_name="tarefas",
            name="titulo",
            field=models.CharField(default="sem título", max_length=255),
        ),
        migrations.AlterField(
            model_name="tarefas",
            name="data_fim",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data de fim"
            ),
        ),
    ]
