# Generated by Django 6.1.1 on 2026-10-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_tarefas_data_inicio_tarefas_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefas",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("em_andamento", "Em Andamento"),
                    ("concluida", "Concluída"),
                ],
                max_length=50,
            ),
        ),
    ]
